function check_isNumber(a){var b=/^\d+$/;return(b.test(a))}function active(b,a){$("a#"+b).addClass("active");$("a#"+a).removeClass("active");$("div#"+b).removeAttr("style");$("div#"+a).attr("style","display:none")}function processTime(f,c,k,i,j){var a=new Date();var d=f-a.getHours();var e=c-a.getMinutes();var g=k-a.getSeconds();g--;if(g<0){g=59;e=e-1}else{e=e}if(e<0&&d>0){e=59;d=d-1}else{if(e<0&&d<=0){e=0}else{d=d}}if(g<=9){g="0"+g}if(e<=9){e="0"+e}var b="";if(j==0){if(d>0){b+=d+" giờ "}b+=e+" phút "+g+" giây "}else{if(j==1){if(d>0){b+=d+":"}b+=e+":"+g+""}}if(document.getElementById){document.getElementById(i).innerHTML=b}if(e=="00"&&g=="00"&&d==0){g="00";window.clearTimeout(SD);return false}}function showForm(a){if($("#"+a).css("display")=="none"){$("#"+a).show()}else{$("#"+a).hide()}}function in_array(e,d,c){var b="",a=!!c;if(a){for(b in d){if(d[b]===e){return true}}}else{for(b in d){if(d[b]==e){return true}}}return false}function trim(c,a){var b=(!a)?new RegExp("^\\s+|\\s+$","g"):new RegExp("^"+a+"+|"+a+"+$","g");return c.replace(b,"")}function rtrim(c,a){var b=(!a)?new RegExp("\\s+$"):new RegExp(a+"+$");return c.replace(b,"")}function ltrim(c,a){var b=(!a)?new RegExp("^\\s+"):new RegExp("^"+a+"+");return c.replace(b,"")}function setHtmlVideo(d,c,a){var b="";b+='<object width="'+c+'" height="'+a+'" type="video/quicktime" data="'+d+'">';b+='<param value="'+d+'" name="src">';b+="</object>";return b}function loadKetquaMienbac1(b,a){$.ajax({type:"GET",url:b,data:"",success:function(c){$("#"+a).html(c)}})}function loadKetquaMiennam1(c,b,a){$.ajax({type:"GET",url:c,data:{str_province:b},success:function(d){$("#"+a).html(d)}})}function loadKetquaMientrung1(c,b,a){$.ajax({type:"GET",url:c,data:{str_province:b},success:function(d){$("#"+a).html(d)}})}function format_number_post(a){a=a.toString().replace(/\$|\,/g,"");if(isNaN(a)){a="0"}sign=(a==(a=Math.abs(a)));a=Math.floor(a*100+0.50000000001);cents=a%100;a=Math.floor(a/100).toString();if(cents<10){cents="0"+cents}for(var b=0;b<Math.floor((a.length-(1+b))/3);b++){a=a.substring(0,a.length-(4*b+3))+"."+a.substring(a.length-(4*b+3))}return(((sign)?"":"-")+a)}function reloadCaptcha(a,b){var d=Math.floor(Math.random()*101001);var c=b+"/captcha.php?num="+d;$("img[name="+a+"]").attr("src",c)}function show_prompt(b){var a=prompt("Bạn hãy điền tên đại lý!","");if(a!=null){window.open(b+"&name="+a)}else{if(a==""){window.open(b)}}};

function searchKQ(url_base,pid){
    var ngay = document.getElementById("ngay").value;
    var thang = document.getElementById("thang").value;
    var nam = document.getElementById("nam").value;   
    if(pid >0){
        var url = url_base + '-ngay-' + ngay + '-' + thang + '-' + nam + '-p' + pid + '.html';
    }else{
        var url = url_base + '-ngay-' + ngay + '-' + thang + '-' + nam + '.html';
    }
    window.location.href = url;
}